"""add ai_title_tag

Revision ID: 4139869d458f
Revises: cd6059879489
Create Date: 2024-01-09 14:28:46.234956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4139869d458f'
down_revision: Union[str, None] = 'cd6059879489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_file', sa.Column('ai_title_tag_article', sa.JSON(), nullable=True))
    op.drop_column('youtube_file', 'ai_title_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_file', sa.Column('ai_title_tag', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('youtube_file', 'ai_title_tag_article')
    # ### end Alembic commands ###
