"""add count

Revision ID: 4752241959bc
Revises: 4139869d458f
Create Date: 2024-01-10 08:54:14.794440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4752241959bc'
down_revision: Union[str, None] = '4139869d458f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_file', sa.Column('gemini_text_failed_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_file', 'gemini_text_failed_count')
    # ### end Alembic commands ###
