"""Added

Revision ID: 4b2f03b05142
Revises: e621be575787
Create Date: 2024-01-04 14:23:57.028783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2f03b05142'
down_revision: Union[str, None] = 'e621be575787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_file', 'is_geminai',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('youtube_file', 'is_notion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_file', 'is_notion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('youtube_file', 'is_geminai',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
