"""Added

Revision ID: 9f369aedec15
Revises: 
Create Date: 2024-01-04 14:07:19.832005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f369aedec15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complete_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('save_folder_path', sa.String(), nullable=False),
    sa.Column('complete_file_path', sa.String(), nullable=False),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_youtube', sa.Boolean(), nullable=False),
    sa.Column('is_instar', sa.Boolean(), nullable=False),
    sa.Column('is_x', sa.Boolean(), nullable=False),
    sa.Column('is_thread', sa.Boolean(), nullable=False),
    sa.Column('is_pinterest', sa.Boolean(), nullable=False),
    sa.Column('is_fine', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complete_file_path'),
    sa.UniqueConstraint('save_folder_path')
    )
    op.create_index(op.f('ix_complete_file_id'), 'complete_file', ['id'], unique=False)
    op.create_table('complete_video_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('save_folder_path', sa.String(), nullable=False),
    sa.Column('complete_video_path', sa.String(), nullable=False),
    sa.Column('counted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complete_video_path'),
    sa.UniqueConstraint('save_folder_path')
    )
    op.create_index(op.f('ix_complete_video_file_id'), 'complete_video_file', ['id'], unique=False)
    op.create_table('origin_text_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('youtube_downfile_path', sa.String(length=200), nullable=True),
    sa.Column('youtube_title', sa.String(length=255), nullable=True),
    sa.Column('ai_text', sa.JSON(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('counted', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_youtube', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_origin_text_file_id'), 'origin_text_file', ['id'], unique=False)
    op.create_table('ref_video_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_video_path', sa.String(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('counted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_video_file_id'), 'ref_video_file', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('youtube_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('video_origin_path', sa.String(), nullable=False),
    sa.Column('stream_url', sa.String(), nullable=False),
    sa.Column('save_folder_path', sa.String(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('save_folder_path'),
    sa.UniqueConstraint('stream_url'),
    sa.UniqueConstraint('video_origin_path'),
    sa.UniqueConstraint('youtube_url')
    )
    op.create_index(op.f('ix_youtube_file_id'), 'youtube_file', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_file_id'), table_name='youtube_file')
    op.drop_table('youtube_file')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ref_video_file_id'), table_name='ref_video_file')
    op.drop_table('ref_video_file')
    op.drop_index(op.f('ix_origin_text_file_id'), table_name='origin_text_file')
    op.drop_table('origin_text_file')
    op.drop_index(op.f('ix_complete_video_file_id'), table_name='complete_video_file')
    op.drop_table('complete_video_file')
    op.drop_index(op.f('ix_complete_file_id'), table_name='complete_file')
    op.drop_table('complete_file')
    # ### end Alembic commands ###
