"""add ai_title_tag

Revision ID: cd6059879489
Revises: 85eb3b382660
Create Date: 2024-01-09 14:22:28.554510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6059879489'
down_revision: Union[str, None] = '85eb3b382660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_file', sa.Column('ai_title_tag', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_file', 'ai_title_tag')
    # ### end Alembic commands ###
