"""Added

Revision ID: e621be575787
Revises: 9f369aedec15
Create Date: 2024-01-04 14:11:56.118779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e621be575787'
down_revision: Union[str, None] = '9f369aedec15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_file', sa.Column('is_gpt', sa.Boolean(), nullable=False))
    op.add_column('youtube_file', sa.Column('is_geminai', sa.Boolean(), nullable=True))
    op.add_column('youtube_file', sa.Column('is_notion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_file', 'is_notion')
    op.drop_column('youtube_file', 'is_geminai')
    op.drop_column('youtube_file', 'is_gpt')
    # ### end Alembic commands ###
